"""
auth_bootstrap.py — Generate a production-ready .env.production.example file.

Run this script once to generate a documented environment variable template
for deploying the FixOps CTEM+ platform in an enterprise environment.

Usage:
    python3 auth_bootstrap.py
    python3 auth_bootstrap.py --output /path/to/.env.production.example
    python3 auth_bootstrap.py --org-id acme-corp --origins https://app.acme.com
"""

from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path

# Allow running from any directory
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from core.api_key_manager import APIKeyManager

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[2] / ".env.production.example"
)

DEFAULT_ORIGINS = "https://app.aldeci.com"


# ---------------------------------------------------------------------------
# Generation helpers
# ---------------------------------------------------------------------------


def _generate_jwt_secret(length: int = 64) -> str:
    """Return a cryptographically random 64-char hex string for use as a JWT secret."""
    return secrets.token_hex(length // 2)  # token_hex(32) → 64 hex chars


def _generate_example_env(
    api_token: str,
    jwt_secret: str,
    *,
    allowed_origins: str = DEFAULT_ORIGINS,
    org_id: str = "your-org-id",
    db_host: str = "db.internal",
    db_port: int = 5432,
    db_name: str = "fixops_prod",
    db_user: str = "fixops",
    db_password: str = "CHANGE_ME",
) -> str:
    """Return the content of the .env.production.example file."""

    return f"""\
# =============================================================================
# FixOps CTEM+ Platform — Production Environment Variables
# =============================================================================
#
# IMPORTANT: This is an EXAMPLE file.  Do NOT commit real secrets to VCS.
#
# Usage:
#   1. Copy this file:  cp .env.production.example .env
#   2. Replace every placeholder value with real secrets.
#   3. Rotate FIXOPS_API_TOKEN and FIXOPS_JWT_SECRET before first production use.
#   4. Ensure .env is listed in .gitignore.
#
# Generated by: suite-core/core/auth_bootstrap.py
# =============================================================================


# =============================================================================
# Authentication
# =============================================================================

# Primary API token used by seed scripts, CI pipelines, and internal services.
# Format: <prefix>_sk_<base64url-32-bytes>  (Stripe-style)
# ⚠️  THIS IS AN EXAMPLE KEY — rotate before use!
FIXOPS_API_TOKEN={api_token}

# 64-character hex secret for signing JWT tokens (HS256).
# Generate a fresh one with:  python3 -c "import secrets; print(secrets.token_hex(32))"
# ⚠️  THIS IS AN EXAMPLE SECRET — rotate before use!
FIXOPS_JWT_SECRET={jwt_secret}

# Deployment mode.  Options: development | staging | enterprise
FIXOPS_MODE=enterprise

# Comma-separated list of allowed CORS origins.
FIXOPS_ALLOWED_ORIGINS={allowed_origins}

# Organisation identifier used for multi-tenant isolation.
FIXOPS_ORG_ID={org_id}


# =============================================================================
# Database
# =============================================================================

# PostgreSQL connection URL.
# Format: postgresql://<user>:<password>@<host>:<port>/<dbname>
FIXOPS_DB_URL=postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}

# Individual DB components (alternative to DB_URL if your driver prefers them).
FIXOPS_DB_HOST={db_host}
FIXOPS_DB_PORT={db_port}
FIXOPS_DB_NAME={db_name}
FIXOPS_DB_USER={db_user}
FIXOPS_DB_PASSWORD={db_password}


# =============================================================================
# Rate Limiting
# =============================================================================

# Maximum requests per minute per API key.
FIXOPS_RATE_LIMIT_PER_MIN=600

# Maximum burst size for short-lived traffic spikes.
FIXOPS_RATE_LIMIT_BURST=100


# =============================================================================
# LLM / AI Providers
# =============================================================================

# OpenAI API key for GPT-based analysis and remediation suggestions.
OPENAI_API_KEY=sk-...REPLACE_ME...

# Anthropic Claude API key (optional — used for consensus engine).
ANTHROPIC_API_KEY=sk-ant-...REPLACE_ME...

# Default LLM model for automated analysis.
FIXOPS_LLM_MODEL=gpt-4o-mini


# =============================================================================
# Integrations
# =============================================================================

# Jira integration (for ticket creation from playbook actions).
JIRA_URL=https://your-org.atlassian.net
JIRA_USER=fixops-bot@your-org.com
JIRA_API_TOKEN=REPLACE_ME
JIRA_PROJECT_KEY=SEC

# Slack integration (for alert notifications).
SLACK_BOT_TOKEN=xoxb-REPLACE_ME
SLACK_CHANNEL=#security-alerts

# GitHub integration (for code-to-cloud tracing and PR comments).
GITHUB_TOKEN=ghp_REPLACE_ME
GITHUB_ORG=your-org


# =============================================================================
# Feature Flags
# =============================================================================

# Enable experimental GNN-based attack graph analysis.
FIXOPS_ENABLE_GNN=false

# Enable real-time CVE feed ingestion.
FIXOPS_ENABLE_CVE_FEED=true

# Enable MCP (Model Context Protocol) gateway.
FIXOPS_ENABLE_MCP=false


# =============================================================================
# Observability
# =============================================================================

# Log level.  Options: DEBUG | INFO | WARNING | ERROR
FIXOPS_LOG_LEVEL=INFO

# Sentry DSN for error tracking (optional).
SENTRY_DSN=https://...@sentry.io/...
"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a production .env.production.example for FixOps."
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="Path to write the example env file (default: repo-root/.env.production.example)",
    )
    parser.add_argument(
        "--org-id",
        default="your-org-id",
        help="Organisation identifier to embed in the example (default: your-org-id)",
    )
    parser.add_argument(
        "--origins",
        default=DEFAULT_ORIGINS,
        help=f"Allowed CORS origins (default: {DEFAULT_ORIGINS})",
    )
    args = parser.parse_args()

    # Generate example credentials
    mgr = APIKeyManager()
    example_api_token = mgr.generate_api_key(description="Example bootstrap key")
    example_jwt_secret = _generate_jwt_secret()

    content = _generate_example_env(
        api_token=example_api_token,
        jwt_secret=example_jwt_secret,
        allowed_origins=args.origins,
        org_id=args.org_id,
    )

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")

    print(f"[auth_bootstrap] Written: {output_path}")
    print()
    print("  Example API token  (ROTATE BEFORE USE):")
    print(f"    FIXOPS_API_TOKEN={example_api_token}")
    print()
    print("  Example JWT secret (ROTATE BEFORE USE):")
    print(f"    FIXOPS_JWT_SECRET={example_jwt_secret}")
    print()
    print("  Key hash (for storage):")
    print(f"    {mgr.hash_api_key(example_api_token)}")
    print()
    print("  Next steps:")
    print("    1. Copy .env.production.example → .env")
    print("    2. Replace all placeholder values with real secrets")
    print("    3. Add .env to .gitignore")
    print("    4. Run:  python3 seed_compliance.py  (with FIXOPS_API_TOKEN set)")


if __name__ == "__main__":
    main()
