from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.finding_input import FindingInput


T = TypeVar("T", bound="NavigatorLayerRequest")


@_attrs_define
class NavigatorLayerRequest:
    """Request to generate a MITRE ATT&CK Navigator layer JSON.

    Attributes:
        findings (list[FindingInput]): Security findings to include in the Navigator layer
        layer_name (str | Unset): Display name for the ATT&CK Navigator layer Default: 'FixOps Application Vulnerability
            Coverage'.
        description (str | Unset): Layer description Default: 'Auto-generated by FixOps MITRE ATT&CK Mapper'.
    """

    findings: list[FindingInput]
    layer_name: str | Unset = "FixOps Application Vulnerability Coverage"
    description: str | Unset = "Auto-generated by FixOps MITRE ATT&CK Mapper"
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        findings = []
        for findings_item_data in self.findings:
            findings_item = findings_item_data.to_dict()
            findings.append(findings_item)

        layer_name = self.layer_name

        description = self.description

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "findings": findings,
            }
        )
        if layer_name is not UNSET:
            field_dict["layer_name"] = layer_name
        if description is not UNSET:
            field_dict["description"] = description

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.finding_input import FindingInput

        d = dict(src_dict)
        findings = []
        _findings = d.pop("findings")
        for findings_item_data in _findings:
            findings_item = FindingInput.from_dict(findings_item_data)

            findings.append(findings_item)

        layer_name = d.pop("layer_name", UNSET)

        description = d.pop("description", UNSET)

        navigator_layer_request = cls(
            findings=findings,
            layer_name=layer_name,
            description=description,
        )

        navigator_layer_request.additional_properties = d
        return navigator_layer_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
