from enum import Enum


class ThreatIndicator(str, Enum):
    ANOMALOUS_DOWNLOAD = "ANOMALOUS_DOWNLOAD"
    DATA_HOARDING = "DATA_HOARDING"
    OFF_HOURS_ACTIVITY = "OFF_HOURS_ACTIVITY"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    PRIVILEGE_ABUSE = "PRIVILEGE_ABUSE"
    RESIGNATION_RISK = "RESIGNATION_RISK"
    UNAUTHORIZED_TOOL = "UNAUTHORIZED_TOOL"
    UNUSUAL_ACCESS = "UNUSUAL_ACCESS"

    def __str__(self) -> str:
        return str(self.value)
