#!/usr/bin/env python3
"""
ALdeci Artifact Ingestion — Feed real security data into ALdeci APIs
=====================================================================
Feeds SBOM, CVE, SARIF, CNAPP, VEX, and business context into ALdeci
ingestion endpoints. Uses artifacts generated by the Threat Architect.

Usage:
    python scripts/feed_artifacts.py
    python scripts/feed_artifacts.py --verbose

Pillar: V3 (Decision Intelligence) + V10 (CTEM Full Loop)
"""

import json
import os
import sys
import time
import urllib.request
import urllib.error
import urllib.parse
from pathlib import Path

# ── Config ──────────────────────────────────────────────────────────────

BASE_URL = os.getenv("ALDECI_BASE_URL", "http://localhost:8000")
API_TOKEN = os.getenv(
    "FIXOPS_API_TOKEN",
    "aVFf3-1e7EmlXzx37Y8jaCx--yzpd4OJroyIdgXH-vFiylmaN0FDl2vIOAfBA_Oh",
)
VERBOSE = "--verbose" in sys.argv or "-v" in sys.argv

FEEDS_DIR = Path(__file__).parent.parent / ".claude" / "team-state" / "threat-architect" / "feeds"

# ── Colors ──────────────────────────────────────────────────────────────

GREEN = "\033[92m"
RED = "\033[91m"
CYAN = "\033[96m"
BOLD = "\033[1m"
DIM = "\033[2m"
RESET = "\033[0m"

# ── HTTP helpers ────────────────────────────────────────────────────────

def post_json(path: str, data: dict, timeout: int = 30) -> tuple:
    """POST JSON body to API endpoint."""
    url = f"{BASE_URL}/{path.lstrip('/')}"
    headers = {"X-API-Key": API_TOKEN, "Content-Type": "application/json"}
    body = json.dumps(data).encode()
    req = urllib.request.Request(url, data=body, headers=headers, method="POST")
    start = time.monotonic()
    try:
        resp = urllib.request.urlopen(req, timeout=timeout)
        elapsed = (time.monotonic() - start) * 1000
        raw = resp.read().decode()
        try:
            return resp.getcode(), json.loads(raw), elapsed
        except json.JSONDecodeError:
            return resp.getcode(), raw, elapsed
    except urllib.error.HTTPError as e:
        elapsed = (time.monotonic() - start) * 1000
        raw = e.read().decode()
        try:
            return e.code, json.loads(raw), elapsed
        except Exception:
            return e.code, raw, elapsed
    except Exception as e:
        elapsed = (time.monotonic() - start) * 1000
        return 0, str(e), elapsed


def post_multipart(path: str, file_path: Path, field_name: str = "file", timeout: int = 30) -> tuple:
    """POST file as multipart/form-data to API endpoint."""
    import mimetypes
    url = f"{BASE_URL}/{path.lstrip('/')}"
    boundary = "----ALdeciArtifactBoundary"

    content_type = mimetypes.guess_type(str(file_path))[0] or "application/octet-stream"
    file_data = file_path.read_bytes()

    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="{field_name}"; filename="{file_path.name}"\r\n'
        f"Content-Type: {content_type}\r\n"
        f"\r\n"
    ).encode() + file_data + f"\r\n--{boundary}--\r\n".encode()

    headers = {
        "X-API-Key": API_TOKEN,
        "Content-Type": f"multipart/form-data; boundary={boundary}",
    }
    req = urllib.request.Request(url, data=body, headers=headers, method="POST")
    start = time.monotonic()
    try:
        resp = urllib.request.urlopen(req, timeout=timeout)
        elapsed = (time.monotonic() - start) * 1000
        raw = resp.read().decode()
        try:
            return resp.getcode(), json.loads(raw), elapsed
        except json.JSONDecodeError:
            return resp.getcode(), raw, elapsed
    except urllib.error.HTTPError as e:
        elapsed = (time.monotonic() - start) * 1000
        raw = e.read().decode()
        try:
            return e.code, json.loads(raw), elapsed
        except Exception:
            return e.code, raw, elapsed
    except Exception as e:
        elapsed = (time.monotonic() - start) * 1000
        return 0, str(e), elapsed


# ── Feed functions ──────────────────────────────────────────────────────

def feed_artifact(name: str, endpoint: str, file_path: Path, use_json: bool = False) -> bool:
    """Feed a single artifact file into ALdeci API."""
    print(f"\n  {BOLD}Feeding: {name}{RESET}")
    print(f"    File: {file_path.name} ({file_path.stat().st_size:,} bytes)")

    if not file_path.exists():
        print(f"    {RED}✗ File not found{RESET}")
        return False

    if use_json:
        # Read and POST as JSON body
        with open(file_path) as f:
            data = json.load(f)
        code, resp, ms = post_json(endpoint, data)
    else:
        # POST as multipart file upload
        code, resp, ms = post_multipart(endpoint, file_path)

    ok = code in (200, 201, 202)
    status = f"{GREEN}✓{RESET}" if ok else f"{RED}✗{RESET}"
    print(f"    {status} {endpoint} → HTTP {code} ({ms:.0f}ms)")

    if VERBOSE and isinstance(resp, dict):
        detail = json.dumps(resp, indent=2)[:300]
        for line in detail.split("\n"):
            print(f"    {DIM}{line}{RESET}")

    return ok


def feed_brain_ingest(name: str, endpoint: str, file_path: Path) -> bool:
    """Feed data into brain ingestion endpoints."""
    print(f"\n  {BOLD}Brain Ingest: {name}{RESET}")
    print(f"    File: {file_path.name}")

    if not file_path.exists():
        print(f"    {RED}✗ File not found{RESET}")
        return False

    with open(file_path) as f:
        data = json.load(f)

    # For CVE feed, ingest each CVE into brain
    if "cve" in name.lower():
        cves = data.get("cves", data.get("vulnerabilities", []))
        count = 0
        for cve in cves[:10]:  # Limit to first 10
            cve_payload = {
                "cve_id": cve.get("cve_id", cve.get("id", "")),
                "severity": cve.get("severity", "MEDIUM"),
                "cvss_score": cve.get("cvss_v31", cve.get("cvss_score", 5.0)),
                "description": cve.get("description", "")[:500],
                "published": cve.get("published", "2026-01-01"),
            }
            code, _, _ = post_json(endpoint, cve_payload)
            if code in (200, 201):
                count += 1
        print(f"    {GREEN}✓{RESET} Ingested {count}/{len(cves)} CVEs into brain graph")
        return count > 0

    # For SARIF findings
    if "sarif" in name.lower():
        runs = data.get("runs", [])
        count = 0
        for run in runs:
            for result in run.get("results", [])[:10]:
                finding = {
                    "finding_id": result.get("ruleId", "UNKNOWN"),
                    "title": result.get("message", {}).get("text", ""),
                    "severity": result.get("level", "warning"),
                    "source": "sarif",
                    "tool": run.get("tool", {}).get("driver", {}).get("name", "unknown"),
                }
                code, _, _ = post_json("api/v1/brain/ingest/finding", finding)
                if code in (200, 201):
                    count += 1
        print(f"    {GREEN}✓{RESET} Ingested {count} SARIF findings into brain graph")
        return count > 0

    return False


# ── Main ────────────────────────────────────────────────────────────────

def main():
    print(f"\n{BOLD}{CYAN}{'═' * 60}{RESET}")
    print(f"{BOLD}{CYAN}  ALdeci Artifact Ingestion — Feed Real Data{RESET}")
    print(f"{BOLD}{CYAN}  Source: {FEEDS_DIR}{RESET}")
    print(f"{BOLD}{CYAN}{'═' * 60}{RESET}")

    if not FEEDS_DIR.exists():
        print(f"\n  {RED}ERROR: Feeds directory not found: {FEEDS_DIR}{RESET}")
        print("  Run the threat architect to generate artifacts first.")
        sys.exit(1)

    results = []
    today = "2026-03-01"

    # 1. SBOM ingestion
    sbom_file = FEEDS_DIR / f"sbom-ecommerce-{today}.json"
    if sbom_file.exists():
        results.append(("SBOM (CycloneDX)", feed_artifact(
            "SBOM — CycloneDX 1.5", "inputs/sbom", sbom_file)))

    # 2. CVE Feed
    cve_file = FEEDS_DIR / f"cve-feed-ecommerce-{today}.json"
    if cve_file.exists():
        results.append(("CVE Feed", feed_artifact(
            "CVE Feed — NVD format", "inputs/cve", cve_file)))
        # Also ingest into brain graph
        results.append(("CVE → Brain Graph", feed_brain_ingest(
            "CVE data", "api/v1/brain/ingest/cve", cve_file)))

    # 3. SARIF Report
    sarif_file = FEEDS_DIR / f"sarif-ecommerce-{today}.json"
    if sarif_file.exists():
        results.append(("SARIF Report", feed_artifact(
            "SARIF 2.1.0 — Static Analysis", "inputs/sarif", sarif_file)))
        # Also ingest findings into brain graph
        results.append(("SARIF → Brain Graph", feed_brain_ingest(
            "SARIF findings", "api/v1/brain/ingest/finding", sarif_file)))

    # 4. CNAPP Findings
    cnapp_file = FEEDS_DIR / f"cnapp-ecommerce-{today}.json"
    if cnapp_file.exists():
        results.append(("CNAPP Cloud Findings", feed_artifact(
            "CNAPP — AWS Cloud Security", "inputs/cnapp", cnapp_file)))

    # 5. VEX Document
    vex_file = FEEDS_DIR / f"vex-ecommerce-{today}.json"
    if vex_file.exists():
        results.append(("VEX Document", feed_artifact(
            "VEX — Exploitability Assessment", "inputs/vex", vex_file)))

    # 6. Business Context
    context_file = FEEDS_DIR / f"context-ecommerce-{today}.yaml"
    if context_file.exists():
        results.append(("Business Context", feed_artifact(
            "Business Context — YAML", "inputs/context", context_file)))

    # 7. Architecture Design
    design_file = FEEDS_DIR / f"design-ecommerce-{today}.csv"
    if design_file.exists():
        results.append(("Architecture Design", feed_artifact(
            "Architecture Design — CSV", "inputs/design", design_file)))

    # ── Run Brain Pipeline on ingested data ─────────────────────────────
    print(f"\n{BOLD}{CYAN}━━━ Running Brain Pipeline on Ingested Data ━━━{RESET}")
    code, data, ms = post_json("api/v1/brain/pipeline/run", {
        "org_id": "acme-ecommerce",
        "app_id": "ecommerce-platform",
        "trigger": "artifact-ingestion",
    }, timeout=60)
    if code == 200 and isinstance(data, dict):
        run_id = data.get("run_id", "?")
        steps_done = sum(1 for s in data.get("steps", []) if s.get("status") == "completed")
        total_steps = len(data.get("steps", []))
        print(f"  {GREEN}✓{RESET} Brain pipeline completed: {run_id} ({steps_done}/{total_steps} steps)")
        results.append(("Brain Pipeline", True))
    else:
        print(f"  {RED}✗{RESET} Brain pipeline failed: HTTP {code}")
        results.append(("Brain Pipeline", False))

    # ── Summary ─────────────────────────────────────────────────────────
    passed = sum(1 for _, ok in results if ok)
    total = len(results)
    print(f"\n{BOLD}{'═' * 60}{RESET}")
    print(f"{BOLD}  Artifact Ingestion Summary{RESET}")
    print(f"{BOLD}{'═' * 60}{RESET}")

    for name, ok in results:
        status = f"{GREEN}✓ INGESTED{RESET}" if ok else f"{RED}✗ FAILED{RESET}"
        print(f"  [{status}] {name}")

    overall = f"{GREEN}ALL INGESTED{RESET}" if passed == total else f"{RED}{total - passed} FAILED{RESET}"
    print(f"\n  {BOLD}Result: {passed}/{total} — {overall}{RESET}")
    print(f"{BOLD}{'═' * 60}{RESET}\n")

    sys.exit(0 if passed == total else 1)


if __name__ == "__main__":
    main()
