#!/usr/bin/env bash
set -euo pipefail

echo "========================================"
echo "   FixOps One-Click Setup"
echo "========================================"
echo ""

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

generate_secret() {
    python3 -c "import secrets; print(secrets.token_urlsafe(32))"
}

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env}"
DEPLOYMENT_MODE="${DEPLOYMENT_MODE:-docker}"
COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.demo.yml}"

echo "This script bootstraps a ready-to-run FixOps environment without prompts."
echo "Existing configuration will be replaced with fresh, self-contained defaults."

if [[ -f "$ENV_FILE" ]]; then
    cp "$ENV_FILE" "${ENV_FILE}.bak"
    echo -e "${YELLOW}Existing $ENV_FILE backed up to ${ENV_FILE}.bak${NC}"
fi

echo "" > "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "" | tee -a "$ENV_FILE" >/dev/null
echo "# Generated by scripts/setup-wizard.sh" >> "$ENV_FILE"
echo "FIXOPS_ENVIRONMENT=$DEPLOYMENT_MODE" >> "$ENV_FILE"

API_TOKEN="${FIXOPS_API_TOKEN:-$(generate_secret)}"
echo "FIXOPS_API_TOKEN=$API_TOKEN" >> "$ENV_FILE"

echo "" >> "$ENV_FILE"
echo "# Deterministic LLM configuration (can be overridden with real keys)" >> "$ENV_FILE"
echo "FIXOPS_ENABLE_OPENAI=${FIXOPS_ENABLE_OPENAI:-false}" >> "$ENV_FILE"
echo "FIXOPS_ENABLE_ANTHROPIC=${FIXOPS_ENABLE_ANTHROPIC:-false}" >> "$ENV_FILE"
echo "FIXOPS_ENABLE_GEMINI=${FIXOPS_ENABLE_GEMINI:-false}" >> "$ENV_FILE"
echo "FIXOPS_ENABLE_SENTINEL=${FIXOPS_ENABLE_SENTINEL:-false}" >> "$ENV_FILE"
[[ -n "${OPENAI_API_KEY:-}" ]] && echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> "$ENV_FILE"
[[ -n "${ANTHROPIC_API_KEY:-}" ]] && echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" >> "$ENV_FILE"
[[ -n "${GOOGLE_API_KEY:-}" ]] && echo "GOOGLE_API_KEY=$GOOGLE_API_KEY" >> "$ENV_FILE"
[[ -n "${SENTINEL_API_KEY:-}" ]] && echo "SENTINEL_API_KEY=$SENTINEL_API_KEY" >> "$ENV_FILE"

echo "" >> "$ENV_FILE"
echo "# Self-contained service secrets" >> "$ENV_FILE"
echo "MONGO_USERNAME=${MONGO_USERNAME:-fixops}" >> "$ENV_FILE"
echo "MONGO_PASSWORD=${MONGO_PASSWORD:-$(generate_secret)}" >> "$ENV_FILE"
echo "REDIS_PASSWORD=${REDIS_PASSWORD:-$(generate_secret)}" >> "$ENV_FILE"
echo "SECRET_KEY=${SECRET_KEY:-$(generate_secret)}" >> "$ENV_FILE"

echo "" >> "$ENV_FILE"
echo "# Optional integrations (empty by default for offline use)" >> "$ENV_FILE"
echo "FIXOPS_JIRA_TOKEN=${FIXOPS_JIRA_TOKEN:-}" >> "$ENV_FILE"
echo "FIXOPS_CONFLUENCE_TOKEN=${FIXOPS_CONFLUENCE_TOKEN:-}" >> "$ENV_FILE"
echo "FIXOPS_SLACK_WEBHOOK_URL=${FIXOPS_SLACK_WEBHOOK_URL:-}" >> "$ENV_FILE"

echo "" >> "$ENV_FILE"
echo "# Docker compose defaults" >> "$ENV_FILE"
echo "COMPOSE_FILE=$COMPOSE_FILE" >> "$ENV_FILE"

echo "📄 Wrote non-interactive defaults to $ENV_FILE"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Docker is required to continue. Please install Docker and rerun.${NC}"
    exit 1
fi

echo "🧰 Installing Python dependencies into local virtualenv..."
"$ROOT_DIR/scripts/bootstrap.sh"

echo "🐳 Building FixOps Docker image using $COMPOSE_FILE ..."
docker compose -f "$ROOT_DIR/$COMPOSE_FILE" build

echo "🚀 Starting FixOps stack..."
docker compose -f "$ROOT_DIR/$COMPOSE_FILE" up -d

echo ""
echo "========================================="
echo -e "${GREEN}✅ Environment is ready!${NC}"
echo "========================================="
echo ""
echo "- .env generated with safe defaults"
echo "- Python dependencies pre-installed"
echo "- Docker services running via $COMPOSE_FILE"
echo ""
echo "You can now access the services defined in $COMPOSE_FILE."
